minVersion: 0.23.1
changelogPolicy: auto

targets:
  - name: github
    includeNames: /^sentry-lambda-extension$/i
  - name: registry
    apps:
      app:sentry-lambda-extension:
        urlTemplate: https://downloads.sentry-cdn.com/sentry-lambda-extension/{{version}}/{{file}}
        includeNames: /^sentry-lambda-extension$/i

requireNames:
  - /^sentry-lambda-extension$/
