name: Build Binary Release

on:
  push:
    branches:
      - release/**

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Binary
        run: scripts/build.sh
        env:
          BUILD_ARCH: x86_64

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}
          path: target/sentry-lambda-extension
