name: Build Binary Release

on:
  push:
    branches:
      - release/**

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Build in Docker
      #   run: scripts/docker-build-linux.sh
      #   env:
      #     BUILD_ARCH: x86_64
      #     RELAY_FEATURES: ssl

      # - name: Bundle Debug File
      #   run: |
      #     cd target/x86_64-unknown-linux-${{ matrix.libc }}/release/
      #     zip relay-Linux${{ matrix.suffix }}-x86_64-debug.zip relay.debug
      #     mv relay relay-Linux${{ matrix.suffix }}-x86_64

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ github.sha }}
      #     path: target/x86_64-unknown-linux-${{ matrix.libc }}/release/relay-Linux${{ matrix.suffix }}-x86_64*
