name: Build Binary

on:
  push:
    branches:
      - release/**

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Binary
        run: |
          scripts/build-in-docker.sh
          ls -alh target/x86_64-unknown-linux-gnu/release/sentry-lambda-extension
          ls -alh target
          ls -alh .
          pwd

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}
          path: target/x86_64-unknown-linux-gnu/release/sentry-lambda-extension
